### ISSUE TITLE
Emphasize the importance of the test suite in the track README

### ISSUE THREAD

**Issue by kytrinyx** [exercism/request-new-language-track#10]
From @parkerl in #9:

> I wonder if in this file or maybe the TRACK_README we should emphasize that the tests are really the fundamental "product" that Exercism delivers. Utmost care should be taken when crafting a track's test suite.

The file in question is https://github.com/exercism/request-new-language-track/blob/master/TRACK_README.md

**Comment by parkerl** [comment]
I think #13 closed this.
