### ISSUE TITLE
Request Bitcoin Track

### ISSUE THREAD

**Issue by willcl-ark** [exercism/request-new-language-track#104]
**What programming language should we add?**

Bitcoin

**What is the official website for the language?**

Doesn't really fit, but: https://bitcoincore.org

**Is this a language that comes in many variants? If so, which variant should we support?**

This track will be based in Python, but will have concepts relating to:
* blockchain analysis: building + using relational databases
* cryptography: key pair generation, hashing
* constructing valid bitcoin transactions, signing them and broadcasting them
* generating new block templates for mining
* using Bitcoin's Forth-like Scripting language to create advanced transactions

**Does the language have an official logo?** If so
- please include a link to an example
- please list the attribution rights of that logo
 
 https://bitcoin.org/img/icons/logotop.svg?1625145073

I believe this logo is FOSS, but will clarify

**Is there a testing framework available for the language?**

N/A. Current plan, pending any issues, is to embed a copy of a public Bitcoin Signet ("testing network) into the test-framework image, so that the test runner can return exact results as per the live Bitcoin Blockchain.

You can read more about the default public Signet [here](https://en.bitcoin.it/wiki/Signet). The current Blockchain size of this Signet is ~116 MB, which should fit inside a test-runner container. The test-runner would also include pre-built Bitcoin Core binaries which would run the RPC server that students' requests would poll against.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so
- what is Prism's canonical spelling for the language?
- what file extensions should be highlighted?

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

N/A

**Who will be leading the effort to launch the track?**

Myself, @willcl-ark

**Comment by kytrinyx** [comment]
It looks like this was missed—so sorry about replying so late!

At the moment Exercism is designed to teach programming languages themselves, not tools, libraries, frameworks, computer science, or other broader topics within the area of programming.

While we may expand the scope in the future, we cannot currently support this as a track / course on Exercism.
