### ISSUE TITLE
Idea: Libraries - start with TensorFlow

### ISSUE THREAD

**Issue by lynnlangit** [exercism/request-new-language-track#108]
**What programming language should we add?** TensorFlow (it's a ML library and NOT a language)

**What is the official website for the language?** https://www.tensorflow.org/

**Is this a language that comes in many variants? If so, which variant should we support?** TensorFlow 2

**Does the language have an official logo?** 
https://www.tensorflow.org/resources/images/tf-logo-card-16x9.png - Google logo / library

**Is there a testing framework available for the language?**
Yes - link to article --> https://medium.com/@burnmg/software-testing-in-tensorflow-2-0-33c440ca908c

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** no - it's NOT a language, it's a library. TF itself is written in C++, but it's used via Python wrappers (Keras),  .py

**If it is not supported by Prism.js, what is the closest supported language it maps to?** Python

**Who will be leading the effort to launch the track?** me (Lynn Langit)

**Comment by iHiD** [comment]
Hey again 🙂 

So at the moment, we only do languages. This is a deliberate decision on a few axes, but not least the desire to do one thing really well first, then expand once we've done that. Another challenge is that there would be a lot less standadisation across different libraries compared to languages (e.g. a track on React is going to be very different from one on Tensorflow).

But I do love the idea of having a side of Exercism for libraries - we just need to edge our way to that point, and if/when we do, Tensorflow would be at the top of my personal list.

**Comment by lynnlangit** [comment]
I completely understand, given the massive amount of effort going on in the platform now.  I'll keep checking in here as the evolution continues.

**Comment by iHiD** [comment]
Thanks! 🙂
