### ISSUE TITLE
Improve flow of continuous integration template issue

### ISSUE THREAD

**Issue by kytrinyx** [exercism/request-new-language-track#11]
From @jtigger in #9 

> I wonder if the instruction could be clearer if it flowed like this:
> 
> - what — in simplest terms possible state what is required with no rationale, just raw requirements.
> - why — explain the thinking behind the what.
> - how — give detailed hints/tips/examples to achieve the what.

The document in question is `TRAVIS` in the root of the repository: https://github.com/exercism/request-new-language-track/blob/master/TRAVIS

**Comment by kotp** [comment]
Because of the rename, the link to that document is now:

https://github.com/exercism/request-new-language-track/blob/master/TRAVIS.md

**Comment by kytrinyx** [comment]
I ended up moving the bit about continuous integration to the launch instructions in the docs repo, instead of opening a specific issue about it up front. I'm going to close this.
