### ISSUE TITLE
Rescript

### ISSUE THREAD

**Issue by tkovs** [exercism/request-new-language-track#110]
**What programming language should we add?**
Rescript

**What is the official website for the language?**
https://rescript-lang.org/

**Is this a language that comes in many variants? If so, which variant should we support?**
No

**Does the language have an official logo?** If so
- please include a link to an example
- please list the attribution rights of that logo

Link: https://rescript-lang.org/static/brand/rescript-brandmark.svg
Attribution rights: [I do not know](https://rescript-lang.org/brand)

**Is there a testing framework available for the language?**
Yes. Rescript can use [jest](https://jestjs.io/pt-BR/).

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so
- what is Prism's canonical spelling for the language?
- what file extensions should be highlighted?
rescript is not supported by Prism. The rescript files are `.res` files.

**If it is not supported by Prism.js, what is the closest supported language it maps to?**
Reason.

**Who will be leading the effort to launch the track?**
I can do it.

**Comment by iHiD** [comment]
Hello. I believe there is an intention to rename the `reasonml` track to be `rescript`. @ErikSchierboom Do you have details on this pls?

**Comment by ErikSchierboom** [comment]
Yes, there is an ongoing effort to rename the reasonml track to rescript. See https://github.com/exercism/reasonml/issues/162
