### ISSUE TITLE
Request for COBOL track

### ISSUE THREAD

**Issue by axtens** [exercism/request-new-language-track#114]
**What programming language should we add?**
COBOL

**What is the official website for the language?**
No official website, only websites for variants.

**Is this a language that comes in many variants? If so, which variant should we support?**
GnuCOBOL https://gnucobol.sourceforge.io/

**Does the language have an official logo?** If so
For GnuCOBOL, https://gnucobol.sourceforge.io/images/shire_200.png Licensed under CC-BY-SA 2.0.

**Is there a testing framework available for the language?**
1. https://github.com/OlegKunitsyn/gcblunit
2. https://sites.google.com/site/cobolunit/
3. https://github.com/neopragma/cobol-unit-test/wiki

**Is this language listed as 'supported' by [Highlightjs]
No

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**
Nothing

**Who will be leading the effort to launch the track?**
@axtens

**Comment by kytrinyx** [comment]
Here you go: https://github.com/exercism/gnucobol/issues/1

Thanks for adding COBOL! Getting new people up to speed in this language seems like a good idea, considering all the codebases out there that are going to need people maintaining it after the original authors retire... 💙
