### ISSUE TITLE
V

### ISSUE THREAD

**Issue by cindRoberta** [exercism/request-new-language-track#118]
**What programming language should we add?**
V

**What is the official website for the language?**
https://vlang.io/

**Is this a language that comes in many variants? If so, which variant should we support?**

**Does the language have an official logo?** If so

- please include a link to an example
https://github.com/vlang/v-logo
- please list the attribution rights of that logo
https://github.com/vlang/v-logo/blob/master/LICENSE

**Does the language have an unofficial logo?** If so

- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo

**Is there a testing framework available for the language?**
https://github.com/vlang/v/blob/master/doc/docs.md#testing

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** If so

- what is Highlightjs' canonical spelling for the language?
- what file extensions should be highlighted?

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**

**Who will be leading the effort to launch the track?**

** Some examples
https://github.com/cindRoberta/V

**Comment by iHiD** [comment]
Thanks for this! @cindRoberta You're happy to lead this track to launch? I'm guessing maybe a lot fo the exercises can be ported over from Go?

**Comment by petertseng** [comment]
You may find useful my report from when I explored what it would take to make a V track in September 2020. The report is delivered in https://github.com/exercism/request-new-language-track/issues/74 and https://github.com/petertseng/exercism-v/blob/master/README.md. At your discretion, you may choose to use any, all, or none of what you find there.

**Comment by cindRoberta** [comment]
@iHiD yes, although similar, they have many differences, I see it as a small evolution (a big one would be if it incorporated more FP concepts)
the language is on 0.2 version and probably will have breaking changes

@petertseng thanks

**Comment by iHiD** [comment]
Thanks both. @cindRoberta We'll get the track boostrapped during the week. You might like to schedule a chat (either typing or video) with @ErikSchierboom this week to discuss it (It's his last week working before seasonal holidays). You can email him at erik@exercism.org to set something up 🙂

**Comment by cindRoberta** [comment]
https://github.com/serkonda7/v-coding-challenges

**Comment by iHiD** [comment]
@cindRoberta You've been invited to @exercism/vlang

**Comment by ErikSchierboom** [comment]
Exciting!

**Comment by ErikSchierboom** [comment]
@cindRoberta I've emailed you with the information get started with the track. Enjoy!
