### ISSUE TITLE
Machine Learning with PyTorch

### ISSUE THREAD

**Issue by skmnktl** [exercism/request-new-language-track#119]
**What programming language should we add?**
Machine Learning Using PyTorch

**What is the official website for the language?**
https://pytorch.org/

**Is this a language that comes in many variants? If so, which variant should we support?**
N/A

**Does the language have an official logo?** If so

- please include a link to an example
--- 
- please list the attribution rights of that logo
--- https://pytorch.org/assets/brand-guidelines/PyTorch-Brand-Guidelines.pdf

**Does the language have an unofficial logo?** If so

- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo

**Is there a testing framework available for the language?**
Results can be defined for a given dataset with respect to:
1. with a specific model,
2. with specific model hyperparameters, and
3.  weight initialization.
4. 
**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** If so

Yes, all the code is in Python, so it should flow through.

- what is Highlightjs' canonical spelling for the language?
- what file extensions should be highlighted?

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**

**Who will be leading the effort to launch the track?**
I am happy to lead the effort though help and review from others might be useful in clarifying certain concepts.

**Comment by skmnktl** [comment]
I've been reading other language submissions and responses. The issue with including ML as a Python exercise is that it's far too big to do it justice that way. Perhaps "subtracks" are a reasonable solution? A way to specialize within a given language is missing currently, but it's necessary for these skills to be applied for things.

**Comment by kytrinyx** [comment]
@skmnktl Thanks for the suggestion!

At the moment we don't have a good way to implement a ML track on its own, or a subtrack (as you suggest). While we're not saying "never", we won't have the capacity to implement something like this any time in the next couple of years, at least.

I'm going to go ahead and close the issue for now, since we can't make it actionable.

Thanks again for your interest in kicking something like this off!
