### ISSUE TITLE
WebAssembly (Text Format)

### ISSUE THREAD

**Issue by bushidocodes** [exercism/request-new-language-track#121]
**What programming language should we add?**
WebAssembly

It's a bit ambiguous if this should be called "WebAssembly" or "WebAssembly Text Format" or "WAT" (the file extension). Per the spec, this is essentially the text representation of the WebAssembly specification using S-Expressions. When the text format is translated into binary, the S-Expressions basically get flattened out. Beyond that, the binary and text representations are the same. For example, when the Chrome debugger shows WebAssembly stuff, it automatically translates the binary back to the text representation. 

I think my preference would be to call this WebAssembly to mirror "x86-64 Assembly" and "MIPS Assembly." This seems to be how other tools seem to be describing this, including the Highlight.js link below.

**What is the official website for the language?**
https://webassembly.github.io/spec/core/text/index.html

**Is this a language that comes in many variants? If so, which variant should we support?**

The main variance involves the "host environment" functionality that can be imported into a wasm module. In the browser, this can be any JS function. On server-side runtimes, this is the WebAssembly System Interface (WASI). My suggestion is to use Node.js as the embedding environment, as this provides access to JavaScript imports and the WASI set of functions.

**Does the language have an official logo?** If so

- please include a link to an example
https://github.com/carlosbaraza/web-assembly-logo
- please list the attribution rights of that logo
Creative Commons licensed

**Does the language have an unofficial logo?** If so

No. The official is used extensively.

**Is there a testing framework available for the language?**

No. There is *.wast, which can be used for this purpose, but which is more focused on ensuring spec-compliance.

However, given the fact that WebAssembly is a first-class entity in JavaScript runtimes, we can follow the lead of the JavaScript track and use Jest. This allows the WebAssembly track to essentially port over JavaScript exercises. 

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** If so

It's not on the Markdown provided, but it appears to have been added in version 11. 
https://highlightjs.org/#news-142

- what is Highlightjs' canonical spelling for the language?

It seems to be "wasm"
https://github.com/highlightjs/highlight.js/blob/main/src/languages/wasm.js

- what file extensions should be highlighted?

*.wat

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**

n/a

**Who will be leading the effort to launch the track?**

Sean McBride. My handle is bushidocodes here and on the Exercism platform.

**Comment by iHiD** [comment]
@ErikSchierboom  See https://github.com/bushidocodes/wasm-lagagna/issues/1 also.

**Comment by kytrinyx** [comment]
I went with `WebAssembly` as the name of the language, and `wasm` as the track ID, and added @bushidocodes as a maintainer.

https://github.com/exercism/wasm/issues/1

Thanks for taking this on ✨
