### ISSUE TITLE
Request to add the Unison Programming Language! 🚀

### ISSUE THREAD

**Issue by rlmark** [exercism/request-new-language-track#126]
**What programming language should we add?**
Unison 

**What is the official website for the language?**
https://www.unison-lang.org/

**Is this a language that comes in many variants? If so, which variant should we support?**
No

**Does the language have an official logo?**
SVG link: https://www.unison-lang.org/assets/icon-unison-mark.svg
Attaching a PNG version with color as well: 
![PNG version with color](https://user-images.githubusercontent.com/7613551/166788445-e5891507-4aed-4fe7-a22d-8dcdfba862c3.png)
~For attribution rights, we believe the logo is licensed to "Unison Computing" with the MIT License, but we are checking on that.~
EDIT: Logo is "copywright Unison Computing, all rights reserved" but it is fine for Exercism to use the logo on their website. 

**Does the language have an unofficial logo?**
No

**Is there a testing framework available for the language?**
Testing is a first-class feature of the language. We support testing in lightweight assertions that look like `test> myTest.name = check (myFunction == true)`.

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?**
Not at present. We may add it in the future! 

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**
Haskell 

**Who will be leading the effort to launch the track?**
Rebecca Mark (me! 😁)

**Comment by iHiD** [comment]
@rlmark Great - sounds fantastic. We'll get you a repo set up. You might like to organise a call with @ErikSchierboom for a getting started walkthrough and I suspect @jonathandmiddleton would also love a chat from a community perspective! 🙂 If you drop Erik an email at erik@exercism.org he can get you on our community Slack and you can go from there.

---

@ErikSchierboom You able to do bootstrap this now or do you still need some @kytrinyx magic? Could you liase to get it setup pls?

**Comment by rlmark** [comment]
Wonderful! We are very excited about Exercism. I'll email Erik and get in touch with Jonathan to start the process! As a heads up I just got an update on the attribution of our logo; the edit is listed above, if you need anything from us with regards to being able to display our logo, we'll make it happen! 😁

**Comment by kytrinyx** [comment]
We've got a repository set up for you here:
https://github.com/exercism/unison/issues/1

Welcome! I'm excited to see this happen ✨

**Comment by ErikSchierboom** [comment]
Super excited to see a Unison track! Such an interesting and unique language.
