### ISSUE TITLE
awk

### ISSUE THREAD

**Issue by glennj** [exercism/request-new-language-track#130]
[Work is already in progress](https://github.com/exercism/awk), but for completeness an issue here.

**What programming language should we add?**
awk

**What is the official website for the language?**
n/a

**Is this a language that comes in many variants? If so, which variant should we support?**
Many variants.  
We'll use GNU awk for the track

**Does the language have an official logo?**
Not to my knowledge.

**Does the language have an unofficial logo?** 
There are a couple of books that used an auk on the cover, perhaps that's as close as we get.
Tracked in exercism/awk#10

**Is there a testing framework available for the language?**
No.  
I'll borrow the use of `bats` from the bash track.

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** 

Yes, `awk` and `gawk` are both listed.
- what file extensions should be highlighted?

    `*.awk`
 
**If it is not supported by Highlightjs, what is the closest supported language it maps to?**
n/a

**Who will be leading the effort to launch the track?**
@glennj

**Comment by ErikSchierboom** [comment]
The required repositories have been made and work is in progress! 🎉
