### ISSUE TITLE
Request to add 8th language

### ISSUE THREAD

**Issue by axtens** [exercism/request-new-language-track#132]
**What programming language should we add?**
8th

**What is the official website for the language?**
https://8th-dev.com/

**Is this a language that comes in many variants? If so, which variant should we support?**
This is a non-standard variant of FORTH

**Does the language have an official logo?** If so

- please include a link to an example
https://8th-dev.com/images/logo.webp

- please list the attribution rights of that logo
Not sure what to provide. Site is copyrighted Aaron High-Tech Ltd, Israel

**Does the language have an unofficial logo?** If so
Am not aware of an unofficial logo

**Is there a testing framework available for the language?**
No. I'm writing one. The is an 'assert' word native but that's as far as it goes AFAICT.

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** If so
No.
- what is Highlightjs' canonical spelling for the language?
Does Highlightjs support *any* FORTH-derivative language?
- what file extensions should be highlighted?
.8th

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**
No idea. 
**Who will be leading the effort to launch the track?**
Bruce Axtens, https://github.com/axtens

**Comment by kytrinyx** [comment]
I was slightly apprehensive as I typed in `LANGUAGE=8th TRACK_ID=8th bin/bootstrap` as I have no idea if we make the assumption that all track IDs will be letters and hyphens only, or that track IDs will start with a letter. I'm sure we'll find out! Meanwhile, here it is :-) https://github.com/exercism/8th/issues/1

**Comment by kytrinyx** [comment]
I just realized I forgot to close this when I created the repo. Doing that now.
