### ISSUE TITLE
add solidity

### ISSUE THREAD

**Issue by Aliwahid17** [exercism/request-new-language-track#133]
**What programming language should we add?**
Solidity

**What is the official website for the language?**
[Solidity](https://soliditylang.org/)

**Is this a language that comes in many variants? If so, which variant should we support?**
Solidity v0. 8.15 

**Does the language have an official logo?** If so

- please include a link to an example 
   (https://soliditylang.org/)
- please list the attribution rights of that logo
       Site is copyrighted 

**Does the language have an unofficial logo?** If so
I'm not aware

- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo

**Is there a testing framework available for the language?**

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** If so

- what is Highlightjs' canonical spelling for the language?
- what file extensions should be highlighted?

**If it is not supported by Highlights, what is the closest supported language it maps to?**
no, idea
**Who will be leading the effort to launch the track?**
https://github.com/Aliwahid17

**Comment by kytrinyx** [comment]
Hi @Aliwahid17, thanks for your suggestion. You're in luck, because a solidity track is already in progress!

If you'd like to contribute to the solidity track, feel free to join the discussion here: https://github.com/exercism/solidity/issues/1

I'm going to go ahead and close this as duplicate.

**Comment by kytrinyx** [comment]
See https://github.com/exercism/request-new-language-track/issues/80 for the original issue.
