### ISSUE TITLE
Request to add BQN language

### ISSUE THREAD

**Issue by razetime** [exercism/request-new-language-track#138]
**What programming language should we add?**
BQN

**What is the official website for the language?**
https://mlochbaum.github.io/BQN

**Is this a language that comes in many variants? If so, which variant should we support?**
[CBQN](https://github.com/dzaima/CBQN), the main implementation

**Does the language have an official logo?** 

![Logo SVG](https://github.com/mlochbaum/BQN/blob/master/logo.svg)

**Is there a testing framework available for the language?**

No. only simple assertions are available

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** 
No. 

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**
none, due to differences in symbols. APL will be very inaccurate. 

**Who will be leading the effort to launch the track?**
- [Razetime](https://github.com/razetime)
- [m3m0ry](https://github.com/m3m0ry)

**Comment by m3m0ry** [comment]
I can help with creating a meaningful list of exercises and concepts. But since I am a BQN beginner myself and have 0 knowledge regarding web stuff (Javascript) I won't be much help regarding more technical tasks.

I doubt that Highlighting will be the main issue. The main issue is the editor and how to type in the symbols. I am guessing that it will boil down to editing the code somewhere else, and then copy-paste it in. (or using the offline version altogether)

**Comment by razetime** [comment]
https://abrudz.github.io/lb/bqn will be enough to add a keyboard to the site. highlights will not be hard, a test runner may take time.

**Comment by iHiD** [comment]
Hi both. 

No web knowledge is needed to create a language. We can start this off with a CLI-only version then add online-editor support further down the line (either before or after launch depending on timescales etc).

As you say, the main bit that will be needed will be the test runner, but I don't think that'll be too hard to do. All we need as first version is a test-file where there's some boolean output as to whether all assertions pass or not, and some output to say what's failing (and ideally why!).

@kytrinyx Could you work your magic please and add both @razetime and @m3m0ry to the team :)

**Comment by kytrinyx** [comment]
Done! The opening move is here: https://github.com/exercism/bqn/issues/1

(Holler if I missed a spot!)

**Comment by iHiD** [comment]
(cc @jonathandmiddleton if you'd like to connect 🙂)

**Comment by razetime** [comment]
would like to request adding @gitonthescene to the BQN team.

**Comment by kytrinyx** [comment]
@razetime I've sent the invite to @gitonthescene 👍
