### ISSUE TITLE
requesting chapel track

### ISSUE THREAD

**Issue by lucaferranti** [exercism/request-new-language-track#141]
**What programming language should we add?**
Chapel

**What is the official website for the language?**
https://chapel-lang.org/

**Is this a language that comes in many variants? If so, which variant should we support?**
N/A

**Does the language have an official logo?** 
Yes, 

- link to an example: https://chapel-lang.org/images/chapel-logo.png
- list the attribution rights of that logo: see https://chapel-lang.org/logo.html and https://github.com/chapel-lang/chapel/blob/main/CONTRIBUTORS.md#logo-design

**Does the language have an unofficial logo?** 
Not that I know

**Is there a testing framework available for the language?**
Yes, the built-in UnitTest module: https://chapel-lang.org/docs/modules/packages/UnitTest.html

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** Yes

- what is Highlightjs' canonical spelling for the language? chapel, chpl
- what file extensions should be highlighted? .chpl

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**

**Who will be leading the effort to launch the track?**
@lucaferranti

**Comment by kytrinyx** [comment]
I hadn't heard about Chapel. This looks really neat!

I've put together a repository for you, and there's an issue with some documentation and links here: https://github.com/exercism/chapel/issues/1

You should have an invite to the team that has write permissions on the repository. Once you get yourself situated feel free to ping me and @ErikSchierboom with questions.

**Comment by lucaferranti** [comment]
WoW, this was very fast! Thanks! Looking forward to start working on this

**Comment by ErikSchierboom** [comment]
Great! If you send me an email at erik at exercism.org, I'll link you to some additional resources.

**Comment by lucaferranti** [comment]
@ErikSchierboom I already sent you an email asking to be added to slack. If you have additional resources, I'd be very happy to receive those :)

btw, the markdown link [here](https://exercism.org/docs/building/tracks/new/join-our-community) is not rendered properly

**Comment by kytrinyx** [comment]
That's odd. The markdown in the source looks perfectly reasonable. I wonder if the parser didn't like the mailto: with the parameters.

**Comment by lucaferranti** [comment]
I think it's the white space in the subject, the following works (at least testing on hackmd)

`[erik@exercism.org](mailto:erik@exercism.org?subject=Exercism%20Slack%20Access%20Request)`

**Comment by kytrinyx** [comment]
Yes, of course. In retrospect that is perfectly obvious 😂 Thank you! I'll get that fixed now.
