### ISSUE TITLE
Request to create OpenEuphoria track

### ISSUE THREAD

**Issue by axtens** [exercism/request-new-language-track#145]
**What programming language should we add?**
OpenEuphoria

**What is the official website for the language?**
https://openeuphoria.org/index.wc

**Is this a language that comes in many variants? If so, which variant should we support?**
There is the original language, Euphoria, found at http://www.rapideuphoria.com/. As far as I know, OpenEuphoria has completely supplanted the original. There is a variant called Phix http://phix.x10.mx/

**Does the language have an official logo?** If so

- please include a link to an example
https://openeuphoria.org/logos/80x84-mongoose-color-lite.png

- please list the attribution rights of that logo
unknown at this time

**Is there a testing framework available for the language?**
Yes, there is a unit testing framework described at https://openeuphoria.org/docs/eutest.html#_736_eutestunittesting

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** If so
unknown at this time.

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**
OpenEuphoria has similarities to Lua, Python, REBOL, Nim and Ruby. 

**Who will be leading the effort to launch the track?**
Bruce Axtens @axtens

**Comment by kytrinyx** [comment]
This looks like a fun one!

Here's the repository for you: https://github.com/exercism/openeuphoria/issues/1
