### ISSUE TITLE
Request for ClojureScript track

### ISSUE THREAD

**Issue by ballPointPenguin** [exercism/request-new-language-track#15]
**What programming language should we add?**
ClojureScript

**What is the official website for the language?**
https://clojurescript.org

**Is this a language that comes in many variants? If so, which variant should we support?**
no

**Is there a testing framework available for the language?**
yes https://clojurescript.org/tools/testing

**Who will be leading the effort to launch the track?**
I don't know. Can it be me?
I am also going to draw attention to this in the #ClojureScript channel of the Clojurians Slack.

**Comment by ballPointPenguin** [comment]
Note: there is a great deal that could be borrowed from the Clojure track. However, I believe that ClojureScript is distinct enough to benefit from a track that is independent of Clojure (think common lisp vs emacs lisp vs scheme vs LFE).

**Comment by kytrinyx** [comment]
> I don't know. Can it be me?

Yes! Absolutely.

For the most enjoyable experience, it's worth finding two or three other people who can help you launch it. With 1 person it's possible but often not particularly enjoyable (a bit lonely). With 2 people it's definitely doable. With 3 people something magical happens—the discussions tend to become lively and really inspiring and interesting and fun.

So I'm not warning you off, just suggesting that you find some co-conspirators from a local meetup, or an online community.

I will create the repository for you now.

**Comment by kytrinyx** [comment]
Here you go!
https://github.com/exercism/xclojurescript/issues/1

Feel free to at-mention me if you have questions, of course! We're still working on the documentation, so if anything is unclear in the launch checklist or anywhere else, please open an issue and we can figure out how to improve it.

🎉 🎈

**Comment by kytrinyx** [comment]
- [ ] Run bootstrap script
  `TRACK_ID=<id> LANGUAGE=<language> bin/bootstrap`
- [ ] Turn on [Travis CI][travis]
- [ ] If Windows-specific language, turn on [AppVeyor][appveyor]
- [ ] If Mac-specific language, turn on [Circle CI][circle]
  Add it as a Linux project, then switch it to OS X in _Project Settings -> Build Environment_
- [ ] Add as a submodule to [trackler][]
  `TRACK_ID=<id>; git submodule add https://github.com/exercism/x$TRACK_ID tracks/$TRACK_ID`
- [ ] Create [new team][new-team] for language
- [ ] Add bootstrapped repository to team **with write access**
- [ ] Invite requestor to team

[travis]: https://travis-ci.org/profile/exercism
[appveyor]: https://ci.appveyor.com/projects/new
[circle]: https://circleci.com/gh/organizations/exercism/settings#projects
[trackler]: https://github.com/exercism/trackler/tree/master/tracks
[new-team]: https://github.com/orgs/exercism/new-team

**Comment by kytrinyx** [comment]
OK, it should all be set up now.

**Comment by kytrinyx** [comment]
@ballPointPenguin did you ever have any luck finding people to help you implement this track?

**Comment by kytrinyx** [comment]
Note—it has been 4 months without any contributions to the ClojureScript track, so I've deleted the repository.

If there's any interest in reviving it, we can reopen this issue and bootstrap a new repository.

**Comment by NobbZ** [comment]
Can we formalize this process a bit?

I think some "call us back in a week or we delete" were much nicer than just to delete everything without any warning.

**Comment by kytrinyx** [comment]
Certainly. Would you mind making some suggestions in this issue? https://github.com/exercism/discussions/issues/143

**Comment by kytrinyx** [comment]
For what it's worth, I still have a copy of this repo locally. There were no commits on it other than the ones I have made. I pinged the original requestor back in may and didn't hear back.

**Comment by ballPointPenguin** [comment]
totally reasonable. I reserve hope that I will actually build this track, but since I have not made any commits, it's just as well done in a new repo if/when that time comes.

**Comment by kytrinyx** [comment]
@ballPointPenguin ❤️ It will be a super nice fresh repo when the time comes. Just holler :)

**Comment by LeaveNhA** [comment]
@kytrinyx, I'm really into this!

**Comment by kytrinyx** [comment]
Just to confirm, @LeaveNhA, you are willing to take on the responsibility of building out the clojurescript track?

**Comment by kytrinyx** [comment]
@LeaveNhA I've created a repository here: https://github.com/exercism/clojurescript/issues/1

Please submit individual pull requests with cohesive changes (e.g. documentation, CI setup, logo, individual exercises) to the new repo. I've given you commit access, so you can create branches right in the repo rather than creating a fork. Individual, smaller PRs will give us a few benefits:

* We can help catch things that should have been documented but weren't
* Ongoing development will be visible/transparent to others who are interested in following along
* It will be easier to go back in the git logs to figure things out

If you find things that are odd or confusing, holler.

Welcome :heart: :heart: :heart:

@ballPointPenguin If you have the bandwidth and interest, it looks like maybe the ClojureScript track will have some activity going forward. If you want to help build it, holler, and we will add you to the maintainer team.

**Comment by iHiD** [comment]
Also, if you're not in our Slack and want to be, email me at jeremy@exercism.io and I'll get you invited :)

**Comment by LeaveNhA** [comment]
> Just to confirm, @LeaveNhA, you are willing to take on the responsibility of building out the clojurescript track?

Yes, I’m taking full responsibility, @kytrinyx. 

> Also, if you're not in our Slack and want to be, email me at [jeremy@exercism.io](mailto:jeremy@exercism.io) and I'll get you invited :)

I, already am. Thank you. 😇
