### ISSUE TITLE
New language track: FORTRAN

### ISSUE THREAD

**Issue by sentientmonkey** [exercism/request-new-language-track#26]
**What programming language should we add?**
FORTRAN

**What is the official website for the language?**
No official one from what I can tell, but http://fortranwiki.org/fortran/show/HomePage seems comprehensive.

**Is this a language that comes in many variants? If so, which variant should we support?**
Yup. 😄 I'd suggest fortran 90/95 since it seems the most prevalent and it allows for free form.

**Is there a testing framework available for the language?**
Funit seems to be the best option at the moment.
https://github.com/kleb/nasarb/tree/master/funit

**Who will be leading the effort to launch the track?**
I'd be happy to start, but I am just learning the language. I've ported bob so I feel I have an approach for TDDing fortran. Would love some more help.

**Comment by kytrinyx** [comment]
Sounds great!

Quick note, the language used to be called FORTRAN but was renamed to Fortran (this has caused all sorts of problems in the search on GitHub, which is how I was aware of it). Ref: https://en.wikipedia.org/wiki/Fortran


- [ ] Run bootstrap script
  `TRACK_ID=<id> LANGUAGE=<language> bin/bootstrap`
- [ ] Turn on [Travis CI][travis]
- [ ] If Windows-specific language, turn on [AppVeyor][appveyor]
- [ ] If Mac-specific language, turn on [Circle CI][circle]
  Add it as a Linux project, then switch it to OS X in _Project Settings -> Build Environment_
- [ ] Add as a submodule to [trackler][]
  `TRACK_ID=<id>; git submodule add https://github.com/exercism/x$TRACK_ID tracks/$TRACK_ID`
- [ ] Add the requestor(s) to the exercism/track-maintainers team
- [ ] Create a [new team][new-team] for language
- [ ] Add the bootstrapped repository to the team **with write access**
- [ ] Invite requestor(s) to the new team
- [ ] Make a note of the new track and maintainers for the newsletter

[travis]: https://travis-ci.org/profile/exercism
[appveyor]: https://ci.appveyor.com/projects/new
[circle]: https://circleci.com/gh/organizations/exercism/settings#projects
[trackler]: https://github.com/exercism/trackler/tree/master/tracks
[new-team]: https://github.com/orgs/exercism/new-team

**Comment by sentientmonkey** [comment]
Oh, good to know! I'm just learning the language now - I wanted to use exercism to start, but it didn't exist. Will see if I can get some people that know Fortran to help.

**Comment by kytrinyx** [comment]
> Will see if I can get some people that know Fortran to help.

That's awesome! I have no idea where the Fortran peeps hang out, but I'm sure there's a forum or chat somewhere :)

**Comment by kytrinyx** [comment]
Alrighty, the repo is ready for you.

The launch checklist is here: 

https://github.com/exercism/xfortran/issues/1

If you find things that are odd or confusing, holler.  You can find other track maintainers in the chat room at https://gitter.im/exercism/dev (probably other rooms, too).

Welcome :heart: :heart: :heart:

**Comment by sentientmonkey** [comment]
Awesome, thanks so much for the help!! 🎉

**Comment by ivan-pi** [comment]
Is it possible to reopen this?

The Fortran folks hang out here: https://fortran-lang.discourse.group/

I'd be willing to volunteer for the launch effort.

**Comment by iHiD** [comment]
Hello :) 

There's a fortran track here: https://github.com/exercism/fortran

It needs a maintainer to get it to a good enough state to be live. Would love your help in doing it! I suggest emailing @ErikSchierboom at erik@exercism.io to arrange a time to chat. He can also invite you to our slack where you can as questions of the maintainer team :)
