### ISSUE TITLE
TRACK_README: "Please do not add a README or README.md file to the exercise directory"

### ISSUE THREAD

**Issue by petertseng** [exercism/request-new-language-track#36]
No longer true, because https://github.com/exercism/meta/issues/15 and https://github.com/exercism/discussions/issues/158.

**Comment by NobbZ** [comment]
Well, partially... READMEs are now generated from some metadata and a template. We should point at this process.

**Comment by kytrinyx** [comment]
I'll take a stab at updating this today.
