### ISSUE TITLE
TRACK_README: "Test files should use the following format" section seems too far "Each exercise should have a test suite, ..."

### ISSUE THREAD

**Issue by petertseng** [exercism/request-new-language-track#39]
In the TRACK_README, we have a section about saying "Test files should use the following format", and the maintainers fill in the body of an example test.

I wasn't convinced that that is the right place to put this information, because:

1. If I'm modifying an existing test file, the existing file should give me enough information.
2. If I'm adding a new exercise. I need to know a lot of other information too, and this information is provided below.

Specifically for the second case, further down, we have a bullet point about what goes into an exercise. Test suite, example solution, template file, etc. I was thinking that the information about what would go into a test file would be most helpful here.

I'm obviously unsure, let's talk about what would be best.

**Comment by petertseng** [comment]
Are you serious, (browser)? I didn't want to submit that.

**Comment by petertseng** [comment]
Are you serious, (browser)? I didn't want to submit that. Now I'm forced to edit this and post the issue description anew.

**Comment by petertseng** [comment]
In the TRACK_README, we have a section about saying "Test files should use the following format", and the maintainers fill in the body of an example test.

I wasn't convinced that that is the right place to put this information, because:

1. If I'm modifying an existing test file, the existing file should give me enough information.
2. If I'm adding a new exercise. I need to know a lot of other information too, and this information is provided below.

Specifically for the second case, further down, we have a bullet point about what goes into an exercise. Test suite, example solution, template file, etc. I was thinking that the information about what would go into a test file would be most helpful here.

I'm obviously unsure, let's talk about what would be best.

**Comment by petertseng** [comment]
So what I am saying in this issue is that I thought the ordering of these two things ("test file format" and "what an exercise needs") made sense in #1 but not in #13. As #13 shows, the move was clearly intentional and the express purpose of #13, so I fear I may be in the wrong.

**Comment by kytrinyx** [comment]
One thing that I've been noticing over the past few months, is that I prefer to have as little boilerplate as possible in the track template, and instead have a better guide to implementing a good track repository living in the docs repository.

That way we don't have to worry about trying to keep unmaintained tracks up to date.

Having incomplete boilerplate to fill out means that a lot of new tracks have incomplete boilerplate. I'd rather have less text, but text that makes sense, and then direct new tracks to implement a README that makes sense for their language, and point to examples of how it can be done.

**Comment by macta** [comment]
@kytrinyx I've found it pretty tough going trying to understand how to implement a new language and the relationships between all of the bits (particularly when trying to map a language that is less traditional to a file based approach). Its also confusing what is old and new exercism. E.g. there are lots of things in config.json that other languages seem to specify that I'm not sure what they do

**Comment by kytrinyx** [comment]
@macta I'm so sorry this is confusing!

Now that the old Exercism is gone, I can take a stab at clarifying and simplifying. The `config.json` is described here: https://github.com/exercism/docs/blob/master/language-tracks/configuration/track.md

I'm going to be away for the next few days, but will be back on August 1st. When I am back, let's get together and figure out exactly what is missing, and I will fill in all the gaps.

**Comment by kytrinyx** [comment]
I've dramatically reduced `TRACK_README.md`. I think that until we get our documentation sorted out, it doesn't make sense to point people at all the confusing things.

I've updated the instructions about launching a new track, which I hope are an improvement over what we had: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

 I'm going to close this issue, and we can re-evaluate once the docs are sorted.
