### ISSUE TITLE
Add ReasonML as a new language track

### ISSUE THREAD

**Issue by stevejb71** [exercism/request-new-language-track#41]
**What programming language should we add?**
ReasonML

**What is the official website for the language?**
https://reasonml.github.io/

**Is this a language that comes in many variants? If so, which variant should we support?**
ReasonML is a variant of Ocaml.
BTW... I think it merits its own track because.
1. it's quite different in syntax
2. It's more likely than OCaml to appeal to Javascript developers (because of integrated support to compile to JS + a more familiar syntax).
Some brief discussion was started on the ocaml language track:
https://github.com/exercism/ocaml/issues/230

**Does the language have an official logo?** If so
- please include a link to an example
This looks to be it
https://reasonml.github.io/img/reason.svg
- please list the attribution rights of that logo
I couldn't find any information on this on search

**Does the language have an unofficial logo?** If so
- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo
No unofficial logo as far as I can find.

**Is there a testing framework available for the language?**
https://github.com/glennsl/bs-jest
There may be others.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so
Yes
- what is Prism's canonical spelling for the language?
reason
- what file extensions should be highlighted?
.re

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

**Who will be leading the effort to launch the track?**
Me

**Comment by kytrinyx** [comment]
#
- [ ] Run bootstrap script
  `TRACK_ID=<id> LANGUAGE=<language> bin/bootstrap`
- [ ] Turn on [Travis CI][travis]
- [ ] Add exercism track topics
- [ ] Add as a submodule to [trackler][]
  `TRACK_ID=<id>; git submodule add https://github.com/exercism/$TRACK_ID tracks/$TRACK_ID`
- [ ] Create nested maintainer team $TRACK_ID under exercism/track-maintainers
- [ ] Add the requestor(s) to the exercism/track-maintainers team
- [ ] Update the team's parent https://github.com/orgs/exercism/teams/TRACK_ID/edit
- [ ] Add to v2 list for icon, seeding, twitter
- [ ] Invite requestor(s) to the new team
- [ ] Make a note of the new track and maintainers for the newsletter

[travis]: https://travis-ci.org/profile/exercism
[appveyor]: https://ci.appveyor.com/projects/new
[circle]: https://circleci.com/gh/organizations/exercism/settings#projects
[trackler]: https://github.com/exercism/trackler/tree/master/tracks
[new-team]: https://github.com/orgs/exercism/new-team

**Comment by kytrinyx** [comment]
Ok, here you go! https://github.com/exercism/reasonml/issues/1

I'm closing this, but (as you know) you can always ping me if there's something missing or weird.

**Comment by stevejb71** [comment]
Thanks for setting this up.

**Comment by tejasbubane** [comment]
I was just wondering if anyone requested for reason track - did a google search and landed here. This is great! I will make a PR to add exercises 😃

**Comment by stevejb71** [comment]
That's great. 

I've not tried them yet, but I see tools to convert OCaml code to ReasonML.
https://github.com/reasonml/reason-tools

 The OCaml repo has around 40 exercises, so you could potentially save a lot of time here by converting the example solutions. 

For the tests, it might be better to write by hand. OCaml uses OUnit - something like bs-jest might be preferable for Reason, as it's based off an the Jest JS framework (?)

**Comment by tejasbubane** [comment]
> I've not tried them yet, but I see tools to convert OCaml code to ReasonML.
> https://github.com/reasonml/reason-tools

The first few exercises should be easy to setup, later ones we can convert.

> For the tests, it might be better to write by hand. OCaml uses OUnit - something like bs-jest might be preferable for Reason, as it's based off an the Jest JS framework (?)

Yes, I just did that with the first exercise and sent a PR.

@kytrinyx Can you add me as maintainer for this track please? I would love the get this launched!

**Comment by kytrinyx** [comment]
> Can you add me as maintainer for this track please?

Done!

**Comment by stevejb71** [comment]
This looks like a good way to get started with some exercises:
https://esy.sh/
