### ISSUE TITLE
Language request: Smalltalk

### ISSUE THREAD

**Issue by samWson** [exercism/request-new-language-track#42]
**What programming language should we add?**
Smalltalk. This is a language that has contributed much to modern programming. It is the first Object Oriented Programming language. It pioneered many of the concepts we take for granted in programming today such as byte code interpreting virtual machines, MVC, Object Oriented Programming, and IDE's.

**What is the official website for the language?**
There is no official website. Once Smalltalk was made known at Xerox it seems to have propagated out into the world via many proprietary, and open source dialects. Each one usually has its own implementation, website, maintainers, goals, vision. A great place to start is two of the open source dialects. Squeak is an implementation that sticks close to the original Smalltalk-80 standard. Pharo is an implementation that builds on the original Smalltalk ideas to make something practical for modern programming.

- [Pharo](https://pharo.org/)
- [Squeak](https://squeak.org/)

**Is this a language that comes in many variants? If so, which variant should we support?**
There are many. I believe Pharo to be the best choice here. There is already a community using it for MOOC learning in Europe. It comes with many libraries that make it ready to go for modern programming. The Pharo Launcher tool makes it easy to manage different Pharo images.

**Does the language have an official logo?**
I don't think there ever has been an _official_ logo. Several times the cover of this [Byte magazine](https://archive.org/details/byte-magazine-1981-08) has been used as the basis of a logo e.g. Squeak uses the balloon as its logo. Pharo has its own logo, an example of which can be seen at the [project repository](https://github.com/pharo-project). I haven't yet found the attribution rights to the Pharo logo.

**Is there a testing framework available for the language?**
SUnit, the first of the xUnit testing frameworks, was written for Smalltalk. Pharo includes it by default.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** 
It is. The spelling is _smalltalk_. Smalltalk programming is done inside of images instead of text files. You can _file out_ code into a text file. Smalltalk code in text files is typically suffixed by the _.st_ extension.

**Who will be leading the effort to launch the track?**
Me, because I don't know anyone else more suitable. It would be a new challenge and experience for me, with skills I've never practiced before. I would be happy to take this on because I believe Smalltalk deserves more attention and publicity than it is getting.

I've never met anyone who knew more about Smalltalk than me, mostly because I'm the only person who I know uses Smalltalk. There are plenty of other people who use it. I know this for a fact. There will be people who know far more about Smalltalk than me. But I don't see anyone else getting this started so I want to do it.

**Comment by kytrinyx** [comment]
I think it would be wonderful to support Smalltalk!

I've met a bunch of people who have worked in Smalltalk (and one person who has worked _on_ Smalltalk back in the day), and co-wrote a book with someone who used Smalltalk as their primary language for 14 years.

> But I don't see anyone else getting this started so I want to do it.

That's fantastic. I will get a repository bootstrapped for you!

#
- [ ] Run bootstrap script
  `TRACK_ID=<id> LANGUAGE=<language> bin/bootstrap`
- [ ] Turn on [Travis CI][travis]
- [ ] Add exercism track topics
- [ ] Add as a submodule to [trackler][]
  `TRACK_ID=<id>; git submodule add https://github.com/exercism/$TRACK_ID tracks/$TRACK_ID`
- [ ] Create nested maintainer team $TRACK_ID under exercism/track-maintainers
- [ ] Remove myself from the team
- [ ] Add repository to team with write access
- [ ] Add the requestor(s) to the maintainers team
- [ ] Add to v2 list for icon, seeding, mentor recruitment, twitter
- [ ] Make a note of the new track and maintainer(s) for the newsletter

[travis]: https://travis-ci.org/profile/exercism
[appveyor]: https://ci.appveyor.com/projects/new
[circle]: https://circleci.com/gh/organizations/exercism/settings#projects
[trackler]: https://github.com/exercism/trackler/tree/master/tracks
[new-team]: https://github.com/orgs/exercism/new-team

**Comment by kytrinyx** [comment]
Alrighty, the repo is ready for you.

The tracking issue for launch is here: https://github.com/exercism/pharo/issues/1

Please submit individual pull requests with cohesive changes (e.g. documentation, CI setup, logo, individual exercises) to the new repo. I've given you commit access, so you can create branches right in the repo rather than creating a fork. Individual, smaller PRs will give us a few benefits:

* I can help catch things that should have been documented but weren't
* Ongoing development will be visible/transparent to others who are interested in following along
* It will be easier to go back in the git logs to figure things out

If you find things that are odd or confusing, holler.  You can find other track maintainers in the chat room at https://gitter.im/exercism/dev (probably other rooms, too).

Welcome :heart: :heart: :heart:

**Comment by samWson** [comment]
Thanks. I'll have a look and get started.

**Comment by chriswmercer** [comment]
Hi, did this ever take off? Am interested in learning, then mentoring!

**Comment by samWson** [comment]
Hi @chriswmercer. I'll give you the quick state of play. We managed to get a lot of work done and almost had a working solution for all operating systems. But we still have some bugs and challenges that we haven't been able to overcome. For some of us I think real life has had to take priority and for myself I've been a bit exhausted with a bug I couldn't overcome. I haven't revisited this project since the last Christmas holidays. The long break has been a good thing and I'm hopeful that I can revisit the project and make more progress. For the time being however it is stalled in an unfinished state.

**Comment by chriswmercer** [comment]
Oh I understand completely! I'm not a smalltalk dev (did it in a module at university 20 years ago!) but I can take a look at the repo certainly.
