### ISSUE TITLE
Language request: Ballerina

### ISSUE THREAD

**Issue by kasun04** [exercism/request-new-language-track#44]
**What programming language should we add?**
Ballerina. 
Ballerina is a compiled, transactional, statically and strongly typed programming language with textual and graphical syntaxes. Ballerina incorporates fundamental concepts of distributed system integration into the language and offers a type-safe, concurrent environment to implement microservices with distributed transactions, reliable messaging, stream processing, and workflows.

**What is the official website for the language?**
https://ballerina.io

**Is this a language that comes in many variants? If so, which variant should we support?**
No. 

**Does the language have an official logo?** 
Official Logo: 
https://ballerina.io/img/ballerina-logo.png

Ballerina website is created under Creative Commons Attribution license. 
https://ballerina.io/license-of-site/
If this information is not sufficient, I'll check with the legal department and get back to you. 

**Does the language have an unofficial logo?** 
No

**Is there a testing framework available for the language?**
Yes, it is called 'Testerina'. 
https://ballerina.io/learn/how-to-test-ballerina-code/

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?
No. 

**If it is not supported by Prism.js, what is the closest supported language it maps to?**
Go. 

**Who will be leading the effort to launch the track?**
Me and few other members from Ballerina developer group.

**Comment by kytrinyx** [comment]
I only heard of Ballerina for the first time a couple weeks ago (👋 @lynnlangit) and I'd be really excited to have support for it on Exercism.

(The logo is genius. Can't wait to see what swag you come up with...)

I will bootstrap the repository for you. Would you let me know what the GitHub handles of everyone who will help get this launched? That way I can add you all as maintainers on the new repository.

#
- [ ] Run bootstrap script
  `TRACK_ID=<id> LANGUAGE=<language> bin/bootstrap`
- [ ] Turn on [Travis CI][travis]
- [ ] Add exercism track topics
- [ ] Add as a submodule to [trackler][]
  `TRACK_ID=<id>; git submodule add https://github.com/exercism/$TRACK_ID tracks/$TRACK_ID`
- [ ] Create nested maintainer team $TRACK_ID under exercism/track-maintainers
- [ ] Remove myself from the team
- [ ] Add repository to team with write access
- [ ] Add the requestor(s) to the maintainers team
- [ ] Add to v2 list for icon, seeding, mentor recruitment, twitter
- [ ] Make a note of the new track and maintainer(s) for the newsletter

[travis]: https://travis-ci.org/profile/exercism
[appveyor]: https://ci.appveyor.com/projects/new
[circle]: https://circleci.com/gh/organizations/exercism/settings#projects
[trackler]: https://github.com/exercism/trackler/tree/master/tracks
[new-team]: https://github.com/orgs/exercism/new-team

**Comment by lynnlangit** [comment]
thanks @kytrinyx - please let me know if I can help in any way here.  I am NOT an employee or contractor of WSO2 (the team who are creating this language), rather an interested community member.  Also, when exercism v2 launches, I will, of course, volunteer to mentor this track.

**Comment by kytrinyx** [comment]
Alrighty, the repo is ready for you.

The launch tracking issue is here:

https://github.com/exercism/ballerina/issues/1

I've given you all commit access, so you can create branches right in the repo rather than creating a fork.

Even though you do have commit access, it would be helpful if you use branches and pull requests rather than going straight to master, as ongoing development will be visible/transparent to others who are interested in following along.

If you find things that are odd or confusing, holler.  You can find other track maintainers in the chat room at https://gitter.im/exercism/dev (probably other rooms, too).

Welcome ❤️ 💛 💚 💙 💜 🖤
