### ISSUE TITLE
Language Request for Red

### ISSUE THREAD

**Issue by trosel** [exercism/request-new-language-track#45]
**What programming language should we add?**
Red Lang or Rebol

**What is the official website for the language?**
https://www.red-lang.org/
https://github.com/red

**Is this a language that comes in many variants? If so, which variant should we support?**
Red

**Does the language have an official logo?** If so
https://static.red-lang.org/red-logo.svg
Not sure on license for that...

**Is there a testing framework available for the language?**
There are test scripts on the official repo, but I'm not sure if there's an official framework for pretty printing to console, etc.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?**
No

**If it is not supported by Prism.js, what is the closest supported language it maps to?**
There is a VS Code extension for Red that includes syntax highlighting. https://github.com/red/VScode-extension/blob/master/syntaxes/Red.tmLanguage.json

**Who will be leading the effort to launch the track?**
TBD

**Comment by kytrinyx** [comment]
This sounds like a great language, and would make a good addition to Exercism.

We can't bootstrap a repository for the language track until we have someone willing to take charge of implementing it, so I'll leave this issue open for now, and we can revisit it if someone volunteers to head up development.

**Comment by WildYorkies** [comment]
Some notes on what is / is not possible with Red right now.

1) Red has quick-test, but often roll specific test engines suited to a task or need.
2) CI is only done on github today
3) Modules are coming, but not here yet (this could be an issue when making the exercism directories for exercises
4) An official JSON codec is in the works, but we have a number of existing things to use for now.

> Red is still Alpha, so we need specs to decide what is doable now, versus what needs to wait, e.g. for Full I/O and Modules. If someone champions it, we'll support them as best we can. The team is spread very thin right now though.

**Comment by WildYorkies** [comment]
@Ornataweaver Sorry, I'm not familiar with how that is related to Red :S

**Comment by Ornataweaver** [comment]
It says it's a wallet app for the Ethereum network.

**Comment by WildYorkies** [comment]
@Ornataweaver Interesting! I'd suggest putting in a request for it. Just try to find someone to help with making the track if you don't know Solidity yourself!

**Comment by Ornataweaver** [comment]
Thanks :), I'm trying to find people interested.
Do you wanna join on gitter, discord or any hub?

**Comment by kytrinyx** [comment]
Note: I deleted several comments that were off topic for the issue.

**Comment by trosel** [comment]
@danieloff see my comment here: https://github.com/exercism/request-new-language-track/issues/45#issuecomment-408464950

Red needs a way to test, it needs a way to manage local file imports (the exercises need a directory structure), and it needs a way to parse JSON from http requests for the exercism API.

**Comment by sshine** [comment]
> it needs a way to parse JSON from http requests for the exercism API

I'm not sure why that is the case? Surely you must just be able to run some test command, and `exercism download` / `exercism submit` will take care of distributing the file from/to the Exercism platform.

**Comment by loziniak** [comment]
Hello. I'd like to launch the Red track. Is the Exercism v3 already live, or do I have to follow legacy docs?

**Comment by iHiD** [comment]
Hello. You've caught us in the two month window between the two where there is lots happening in flux. If you follow the legacy docs then your track will get to a state where we can largely script-PR to bring it in line with the new spec. If you email erik@exercism.io he can send you a link to our Slack where we can discuss it all more :)

**Comment by kytrinyx** [comment]
I've created a repo for you here: https://github.com/exercism/red/issues/1

Thank you for helping launch this track!

**Comment by loziniak** [comment]
Thanks! So, all discussions now go to the [Red's repository/issues](https://github.com/exercism/red).

**Comment by iHiD** [comment]
Yes please :)
