### ISSUE TITLE
Are DSLs allowed?

### ISSUE THREAD

**Issue by kzap** [exercism/request-new-language-track#47]
**What programming language should we add?**
Docker, Kubernetes, Ansible, Chef

Apologies if this has been asked before, I did a search but could not find anything. The Exercism platform allows for ramping up in new languages, but what about technologies that use their own DSL or a specific scripting language in a certain way.

Exercism has `bash` but a lot of work is done using DSL's and in the DevOps space there are a lot. Knowing `bash` or `ruby` or `python` does not mean you know how to use Docker, K8s, Ansible etc. You still have to learn those from the ground up.

This may be outside the goals of Exercism but I think it would be a good platform to learn all the above tech, promote best practices and have testable infrastructure as code.

**Comment by kytrinyx** [comment]
Hi @kzap, DSLs and tools are out of scope for Exercism.

Our docs are a mess (and completely unsearchable right now), but we _do_ have something about it here: https://github.com/exercism/docs/blob/master/about/scope-of-a-track.md

I would love to see separate projects that do tackle those sorts of things, but we don't have the bandwidth to consider them on Exercism.

Thank you for asking! (And I'm going to see about sorting out the documentation soon, to make this easier to discover).
