### ISSUE TITLE
Tcl

### ISSUE THREAD

**Issue by sshine** [exercism/request-new-language-track#49]
**What programming language should we add?**

Tcl

**What is the official website for the language?**

[tcl.tk](https://tcl.tk/) or [tcl-lang.org](https://www.tcl-lang.org/) (same).

**Is this a language that comes in many variants? If so, which variant should we support?**

Like LISP, there are [lots of clones](https://wiki.tcl-lang.org/page/Tcl+implementations) of Tcl, but there is one popular implementation called just Tcl/Tk (with Tk being the GUI toolkit).

**Does the language have an official logo?** Yes:
- link to example of logo: https://tcl.tk/images/plume.png
- attribution rights of logo: I've been granted permission by the author. Do you need documentation for this forwarded by email, or do you explicitly need for the logo to be published under a CC license (Wikipedia style), or would it work if I asked the author (David Zolli) to drop by this thread and grant access?

    **Email:**

    > From: Simon Shine <shreddedglory@g...com>
    > Subject: License of plume logo at tcl-lang.org
    > Date: Monday, November 26, 2018 8:13 AM
    > 
    > Dear webmaster at tcl-lang.org
    > 
    > I write to ask about the license of the logo located at:
    > 
    >     https://tcl.tk/images/plume.png
    > 
    > I do this because I intend to create a "language track" for Tcl at Exercism.io.
    > 
    > For each language track there is a logo which they derive from something recognizable for the language.
    > 
    > You can see the logos at:
    > 
    >     https://exercism.io/
    > 
    > Exercism is an open source project with all of their source code available on GitHub:
    > 
    >     https://github.com/exercism
    > 
    > Since the plume appears to be the most recognizable logo for Tcl, I'd like to ask permission to use this logo in derived form for the language track at Exercism.
    > 
    > Is the logo already in a CC-like license, or can permission be granted for this particular use?
    > 
    > Kindly,
    > Simon Shine

    **Response 1:**

    > From: Steve Landers <steve@digital...com>
    > Subject: Re: License of plume logo at tcl-lang.org
    > Date: Monday, November 26, 2018 11:05 AM
    > 
    > Hi Simon,
    > 
    > The plume logo was produced by David Zolli (kroc).  He’ll be able to definitely say whether it is OK to use.
    > 
    > I’ve copied David on this email 
    > 
    > Steve

    **Response 2 (permission granted):**

    > From: David Zolli <david@z...fr>
    > Subject: Re: License of plume logo at tcl-lang.org
    > Date: Monday, November 26, 2018 12:50 PM
    > 
    > Hi Steve and Simon,
    > 
    > Feel free to use it as you need. No problem for me. 
    > 
    > Kind regards,

**Is there a testing framework available for the language?**

Yes, there are [several](https://wiki.tcl-lang.org/page/testing).

I am recommended to use [tcltest](https://wuhrr.wordpress.com/2011/03/28/getting-started-with-tcltest/).

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** Yes:
- Prism's canonical spelling: Tcl, `tcl`.
- file extension: `.tcl`

**Who will be leading the effort to launch the track?**

Me, @sshine. I'll also mentor it.

I believe it will be a low-traffic track like Standard ML.

**Comment by kytrinyx** [comment]
@sshine This is great! I don't need further permission for the logo. We don't use the logo directly, but design an exercism track logo inspired by/based on the logo.

I'll get this repository set up for you in the next few days.
