### ISSUE TITLE
Language request: x86

### ISSUE THREAD

**Issue by bergjohan** [exercism/request-new-language-track#51]
**What programming language should we add?**
x86 or x86-64 assembly

**What is the official website for the language?**
There's no official website, but here are links to the manuals:
[Intel 64 and IA-32 Software Developer Manuals](https://software.intel.com/en-us/articles/intel-sdm)
[AMD64 Architecture Programmer's Manual (Volume 1-5)](https://developer.amd.com/resources/developer-guides-manuals/)

**Is this a language that comes in many variants? If so, which variant should we support?**
I think we should use NASM (The Netwide Assembler). It supports a range of object file formats and has a simple syntax.

**Does the language have an official logo?** If so
- please include a link to an example
- please list the attribution rights of that logo

**Does the language have an unofficial logo?** If so
- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo

**Is there a testing framework available for the language?**
No, but I was thinking we could use [Unity](http://www.throwtheswitch.org/unity) to call the assembly routines. Unity is currently used in the C track. The problem is that Microsoft is using a different calling convention for x86-64 than Linux. There are a few options:
- Use x86 where cdecl is used by default
- Create a Linux only track
- Write a test framework in assembly with our preferred calling convention

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so
- what is Prism's canonical spelling for the language?
nasm
- what file extensions should be highlighted?
asm

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

**Who will be leading the effort to launch the track?**
I'll give it a shot

**Comment by kytrinyx** [comment]
Thanks for opening this up.

How different is MIPS from NASM? We already have a MIPS track, and if possible, I'd love to consolidate efforts if the assembler is similar enough for that to make sense.

**Comment by bergjohan** [comment]
I've been looking at the MIPS track and the tests are programmed in assembly. I was wrong when I said that was an option for x86 because we will have to use syscalls to print characters to the screen, which will be different for Linux and Windows. The MIPS track is using a simulator (MARS) which has syscalls implemented for printing characters.
MIPS and x86 have some similarities and I could probably have a look at the code when implementing examples. But it might be quicker to just paste the examples from C into the Compiler Explorer (https://godbolt.org/) and get the x86 output if you want to get something up and running quickly.
I think we should go with 32-bit x86 to keep it simple. The solutions should work on both Windows and Linux. Using a C test framework has the benefits of cross platform printing to the screen and also readability. It's much easier for the students to see what's going on in the tests if they are written in C instead of assembly.

**Comment by kytrinyx** [comment]
Cool! Thanks for helping think this through. I'll bootstrap up a repository for you. What should we call it, though? `nasm`?

**Comment by kytrinyx** [comment]
Ok cool! My laptop just crashed pretty severely, and I've had to send it away for repairs. As of a few hours ago I'm on a loaner... I might not get this set up until next week.

**Comment by bergjohan** [comment]
I'm sorry to hear that :( No problem!

**Comment by kytrinyx** [comment]
Alrighty, I've got this bootstrapped for you here: https://github.com/exercism/x86/issues/1 🎉
