### ISSUE TITLE
Language request: Shen.

### ISSUE THREAD

**Issue by jaccarmac** [exercism/request-new-language-track#52]
**What programming language should we add?**

Shen.

**What is the official website for the language?**

http://shenlanguage.org/

**Is this a language that comes in many variants? If so, which variant should we support?**

Yes. Using the [CL version](https://github.com/Shen-Language/shen-cl) is likely best but in theory any of the [conforming versions](https://shen-language.github.io/) (scroll down to the table) should work.

**Does the language have an official logo?**

https://github.com/Shen-Language/shen-sources/blob/master/assets/shen_noname.svg

BSD 3-clause per the license in that repo.

**Does the language have an unofficial logo?**

Don't believe so.

**Is there a testing framework available for the language?**

The standard for Shen contains a [testing harness in Shen](https://github.com/Shen-Language/shen-sources/blob/master/tests/README.shen) which could be adapted.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?**

No.

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

I'm thinking `lisp`. `scheme` is another candidate due to `define` but there are significant deviations in syntax from both.

**Who will be leading the effort to launch the track?**

I can. Am still technically a Shen learner but this seems like a neat way to learn it.

**Comment by kytrinyx** [comment]
Cool! I'd never heard of Shen before this. I'll bootstrap up a new repository for you in the next few days. (My laptop crashed and I just got a loaner which has nothing set up on it. I may not get this done until next week)

**Comment by kytrinyx** [comment]
Here you go, @jaccarmac!

https://github.com/exercism/shen/issues/1

**Comment by jaccarmac** [comment]
Whee, thanks so much!
