### ISSUE TITLE
Language request for Gleam

### ISSUE THREAD

**Issue by lpil** [exercism/request-new-language-track#56]
Following on from this twitter thread -> https://twitter.com/exercism_io/status/1125512260300963840

**What programming language should we add?**

Gleam

**What is the official website for the language?**

https://gleam.run

**Is this a language that comes in many variants? If so, which variant should we support?**

No, there is only one variant.

**Does the language have an official logo?** If so
- please include a link to an example
- please list the attribution rights of that logo

Not yet.

**Does the language have an unofficial logo?** If so
- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo

Nope.

**Is there a testing framework available for the language?**

Yes, there are bindings to Erlang's eunit framework.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so
- what is Prism's canonical spelling for the language?
- what file extensions should be highlighted?

No support.
`.gleam` is the extension.

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

Rust.

**Who will be leading the effort to launch the track?**

Me. :)

**Comment by lpil** [comment]
I've started a track here in the mean time -> https://github.com/gleam-lang/exercism-gleam

**Comment by kytrinyx** [comment]
Oh my gosh I am so sorry I missed this. It was buried in hundreds of notifications, and I'm only just clearing everything out. I will set this up for you in the next few days!

**Comment by lpil** [comment]
No worries! I know you are busy :) <3

**Comment by kytrinyx** [comment]
"next few days" was a bit of a lie, but now I am actually on top of things and will _totally_ get this sorted! ❤️

**Comment by lpil** [comment]
"Next few days" by open source standard time ;)

**Comment by kytrinyx** [comment]
Alrighty, the repo is ready for you: https://github.com/exercism/gleam/issues/1

Holler if I missed a spot!

**Comment by lpil** [comment]
Thank you! :)
