### ISSUE TITLE
Request language track: jq

### ISSUE THREAD

**Issue by sshine** [exercism/request-new-language-track#63]
**What programming language should we add?**
jq

**What is the official website for the language?**
https://stedolan.github.io/jq/
https://github.com/stedolan/jq

**Is this a language that comes in many variants? If so, which variant should we support?**
One variant so far.

**Does the language have an official logo?** If so
- https://stedolan.github.io/jq/jq.png
- CC-BY-3.0

**Is there a testing framework available for the language?**
No; the track will have to distribute a test script.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?**
Not yet. I'll consider creating this, but if/when this happens, the answer will unambiguously be:
- jq
- jq

**If it is not supported by Prism.js, what is the closest supported language it maps to?**
None.

**Who will be leading the effort to launch the track?**
Me! I've previously ~worked on~ *bootstrapped* the Tcl track with @glennj.

I've written the Exercism jq Cookbook: exercism/exercism#5055 -- before that I thought that I should write a tutorial/small book, but I didn't like that it wasn't practical enough. So the Exercism-specific use-cases for jq motivated me to publish *something*. I'd like to expand the use-cases a bit beyond that and let Exercism exercises be the problem set.

**Comment by kytrinyx** [comment]
Hi @sshine,

That Exercism jq Cookbook is super sweet!

I've used jq a bit, and it's a fantastic tool. I didn't realize that it was a programming language in addition to being a query syntax. My one worry (not being familiar with it) is whether it's Turing complete in the same way that CSS is Turing complete.

Do people use jq as a full-on language? (And if they don't, should they? I would argue that for CSS the answer is 'no' and 'no', but like I said I don't know enough about jq to have a well-formed opinion).

**Comment by sshine** [comment]
What's a full-on language?

It has an extended standard library ([JBOL](https://github.com/fadado/JBOL)). You can define custom combinators in either imperative or functional style and it has several recursion combinators built-in. So while jq is domain-specific towards stream processing, it is not accidentally Turing-complete like CSS. I would rather compare jq to awk, which is also a stream processor that is not accidentally Turing-complete. On this matter, it seems that the [awk Wikipedia article](https://en.wikipedia.org/wiki/AWK) authors fought a similar battle once:

> While AWK has a limited intended application domain and was especially designed to support one-liner programs, the language is Turing-complete, and even the early Bell Labs users of AWK often wrote well-structured large AWK programs.

The jq language is still too young and ill-understood to boast this claim.

While many useful jq programs are comparable in size to `.exercises[].slug` and are typically embedded in shell scripts, these examples alone reduce jq's image of a swiss army knife to a pair of tweezers. You can create jq programs that are big enough to warrant saving them to file rather than rattle them off in your terminal, and in answering [StackOverflow questions tagged `jq`](https://stackoverflow.com/questions/tagged/jq), I've sometimes had to ([example](https://stackoverflow.com/questions/59104389/merging-two-json-files-based-on-common-key-value-pair-using-jq/59105764#59105764)).

I wouldn't try to implement jq in jq. (Does PHP qualify for this full-on-ness?)

But I might consider it for the [event loop of an IRC bot](https://github.com/athas/EggsML/blob/master/concieggs/irc_event_reader.awk) (awk script), just to prove a point. ;-)

**Comment by iHiD** [comment]
@sshine Is there a reason for closing this? Katrina is off atm but I'm sure she'll reply when back.

**Comment by sshine** [comment]
Yes. I opened the issue as a proposition to create this track, and close
this issue to withdraw it.
