### ISSUE TITLE
Language request for babashka

### ISSUE THREAD

**Issue by porkostomus** [exercism/request-new-language-track#64]
**What programming language should we add?**

babashka

**What is the official website for the language?**

https://github.com/borkdude/babashka/

**Is this a language that comes in many variants? If so, which variant should we support?**

There is only one variant of babashka.

**Does the language have an official logo?** If so
- please include a link to an example

https://github.com/borkdude/babashka/blob/master/logo/babashka.svg

- please list the attribution rights of that logo

[Nikita Prokopov](https://github.com/tonsky)

**Does the language have an unofficial logo?** If so
- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo

no

**Is there a testing framework available for the language?**

Yes, it comes bundled with [clojure.test](https://clojure.github.io/clojure/clojure.test-api.html).

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so
- what is Prism's canonical spelling for the language?
- what file extensions should be highlighted?

No, babashka shares Clojure's syntax and `.clj` extension.

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

Clojure

**Who will be leading the effort to launch the track?**

I will be leading the effort by collaborating with the Bash track (relevant to the language's target domain) and incorporating material from the Clojure track which I am currently maintaining. Michiel Borkent (@[borkdude](https://github.com/borkdude)), the language creator, is very active on my Slack team and available to answer questions.

**Comment by kytrinyx** [comment]
This sounds exciting! I'll get a repository bootstrapped for you in the next couple of days.

**Comment by kytrinyx** [comment]
I'm sorry about the delay here. Things got a bit nuts in the past week. I'm starting to get back on top of things, so I hope to get this done soon.

**Comment by porkostomus** [comment]
No problem, I'm just stoked to be doing this! If it's any help, I already forked the Clojure repo and ported over the exercises and the tests: https://github.com/porkostomus/babashka

For CI, I suppose this may be of help: https://nextjournal.com/a/M4woRraF1pz1zjvjgBY9T?token=Td2LLVyNFmR6rXMEJ7bKZ6

Thanks!

**Comment by kytrinyx** [comment]
Ok here you go! Sorry for the delay.

https://github.com/exercism/babashka/issues/1

I still need to get this added to Travis CI, but unfortunately the travis site is endlessly hanging for me at the moment. I'll keep trying throughout the rest of today.
