### ISSUE TITLE
Broken links for tools repository in README

### ISSUE THREAD

**Issue by javiguajardo** [exercism/request-new-language-track#72]
Hello, the links regarding the `tools` repo in the README seem to be broken.

* [Tools repo](https://github.com/exercism/tools)
* [Tools repo README](https://github.com/exercism/tools#scripts)

![image](https://user-images.githubusercontent.com/12402952/92642799-fc9a9d80-f29d-11ea-96b1-e215857e92ba.png)

Or maybe I need to belong to the `exercism` org to be able to see those repos? 🤷‍♀️

**Comment by iHiD** [comment]
@javiguajardo Thanks. I've pinged @kytrinyx who knows this repo better than me.

**Comment by kytrinyx** [comment]
Ah, I deleted that repo, as all the scripts were woefully out of date, and I was the only one who used any of them. Sorry about the broken links!

**Comment by javiguajardo** [comment]
> Ah, I deleted that repo a few years back, as all the scripts were woefully out of date, and I was the only one who used any of them. Sorry about the broken links!

Thanks for looking into it! I was just clicking around 🙈
