### ISSUE TITLE
template track's bin/fetch-configlet needs to be case-insensitive to `Location:`

### ISSUE THREAD

**Issue by petertseng** [exercism/request-new-language-track#73]
Current version of template bin/fetch-configlet is case-sensitive on `Location:`: https://github.com/exercism/request-new-language-track/blob/6e98d13765f0d361603088dcb9999e0baab6cddd/bin/fetch-configlet#L29

However, since GitHub started outputting lowercase `location:` in February 2020 (reported https://github.com/exercism/configlet/issues/173), this template bin/fetch-configlet won't be able to determine the $VERSION.

Thus, template track's bin/fetch-configlet should be updated to be case-insensitive wrt `Location:`. Otherwise, every new track has to reapply the fix, which is an unnecessary hurdle to getting a track running.

**Comment by petertseng** [comment]
That was probably fixed by https://github.com/exercism/request-new-language-track/pull/76. Not sure, but I'll assume it's good.

**Comment by petertseng** [comment]
No need to assume. I tested the `get_url` in https://github.com/exercism/request-new-language-track/pull/76/files#diff-57a7929c2bd4459c8faf8ae831fc7c8aR37-R40 and find that it is not susceptible to the problem. So this issue is confirmed to be fixed.

**Comment by iHiD** [comment]
Great. Thank you! 🙂
