### ISSUE TITLE
The track template should provide a GitHub Actions template, not a Travis CI template

### ISSUE THREAD

**Issue by petertseng** [exercism/request-new-language-track#81]
As you know from https://github.com/exercism/exercism/issues/5396, the Exercism organisation is moving to GitHub Actions. Therefore, these things should be done to the track template:

* remove .travis.yml 
* badge in TRACK_README.md link to GitHub Actions, not Travis
* (possibly) provide starter workflow template in .github/workflows/*.yml

**Comment by cmccandless** [comment]
> (possibly) provide starter workflow template in .github/workflows/*.yml
I suggest using the [example workflows](https://github.com/exercism/problem-specifications/tree/master/workflows) as a starting point. In fact, maybe this is a better repo to house those. Having "template" copies in two locations is a bit messy.

**Comment by cmccandless** [comment]
@iHiD Sure thing
