### ISSUE TITLE
Addition of VB.NET to Exercism

### ISSUE THREAD

**Issue by ch020** [exercism/request-new-language-track#84]
**What programming language should we add?**
Visual Basic .NET (VB.NET)
**What is the official website for the language?**
https://docs.microsoft.com/en-gb/dotnet/visual-basic/
**Is this a language that comes in many variants? If so, which variant should we support?**
Not really. Just make sure to use the most recent, stable version (I believe Microsoft have stopped releasing new versions)
**Does the language have an official logo?** If so
- please include a link to an example: https://commons.wikimedia.org/wiki/File:VB.NET_Logo.svg
- please list the attribution rights of that logo: Jason Groce, VB.NET Logo, marked as public domain, more details on Wikimedia Commons
**Does the language have an unofficial logo?**
No
**Is there a testing framework available for the language?**
Yes. I believe it is the same as C#. (https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-visual-basic-with-mstest)
**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so
- what is Prism's canonical spelling for the language? Visual Basic
- what file extensions should be highlighted? visual-basic, vb, vba

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

**Who will be leading the effort to launch the track?**
Me

**Comment by iHiD** [comment]
Hello. There is a VB track [here](https://github.com/exercism/vbnet). It's is abandoned pre-launch though. So if you'd like to take up the mantel on that and get it ready for launch, that would be wonderful. If you email erik@exercism.io he can get you set up (cc @ErikSchierboom)
