### ISSUE TITLE
Gosu

### ISSUE THREAD

**Issue by tikrimi** [exercism/request-new-language-track#94]
**What programming language should we add?**

Gosu

Gosu is a statically-typed general-purpose programming language that runs on the Java Virtual Machine. Its influences include Java, C#, and ECMAScript. Development of Gosu began in 2002 internally for Guidewire Software, and the language saw its first community release in 2010 under the Apache 2 license.

Gosu can serve as a scripting language, having free-form Program types (.gsp files) for scripting as well as statically verified Template files (.gst files). Gosu can optionally execute these and all other types directly from source without precompilation, which also distinguishes it from other static languages.

**What is the official website for the language?**

https://gosu-lang.github.io/

**Is this a language that comes in many variants? If so, which variant should we support?**

No variant.

**Does the language have an official logo?** If so

No idea if the logo is official or not, and no idea for attribution rights.

https://gosu-lang.github.io/img/logo-large.png

**Does the language have an unofficial logo?** If so

No idea.

**Is there a testing framework available for the language?**

Yes, Gunit.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so

Gosu is not supported by Prism.js

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

Java or Javascript

**Who will be leading the effort to launch the track?**

I'm still reading the documentation on how to launch a new track. Don't know if I would be able to lead it, but at least we can discuss about it.

**Comment by iHiD** [comment]
@tikrimi Thanks for your interest in creating the new track! Let me know if you decide to go ahead or have any questions :)

**Comment by tikrimi** [comment]
Hi @iHiD

I got a first look. Not so easy to run unit tests with gunit outside the Guidewire IDE (it's a packaged version of Intellij), but it should be ok.
The issue can be with the licensing. In order to run unit tests in a command line way, we will need to download what Guidewire calls an accelerator: [https://marketplace.guidewire.com/ccrz__ProductDetails?sku=A-10124]. I'm not familiar with licenses, and I don't know if why can use it or not.
An alternative can be to write and run unit tests with junit, but I think that for learning purpose, it's better to write code and test with the same language.
By the way, I think I have some home work to do before. I think we can close this issue, and I will reopen it when I will be ready.

**Comment by iHiD** [comment]
OK, thanks @tikrimi
